# Generated by Django 5.1.3 on 2025-07-19 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=150, verbose_name='Nombre de usuario')),
                ('tipo_accion', models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('create', 'Creación'), ('update', 'Actualización'), ('delete', 'Eliminación'), ('view', 'Visualización'), ('other', 'Otra acción')], max_length=10, verbose_name='Tipo de acción')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('modelo_afectado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo afectado')),
                ('objeto_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID del objeto')),
                ('campos_modificados', models.JSONField(blank=True, null=True, verbose_name='Campos modificados')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('navegador', models.TextField(blank=True, null=True, verbose_name='Navegador/Agente')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_actividad', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de actividad',
                'verbose_name_plural': 'Logs de actividad',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['usuario'], name='auditoria_l_usuario_ff713f_idx'), models.Index(fields=['tipo_accion'], name='auditoria_l_tipo_ac_a04560_idx'), models.Index(fields=['fecha_hora'], name='auditoria_l_fecha_h_3e5b3f_idx'), models.Index(fields=['modelo_afectado'], name='auditoria_l_modelo__6b97ff_idx')],
            },
        ),
    ]
