# Generated by Django 5.2.4 on 2025-07-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logactividad',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y hora'),
        ),
    ]
