# Generated by Django 5.2.4 on 2026-04-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Sistema administrativo - Agricola de la Costa San Luis', help_text='Texto que aparece en la pestaña del navegador.', max_length=200, verbose_name='Título de la pestaña')),
                ('site_header', models.CharField(default='Agricola de la Costa San Luis', help_text='Título principal en la pantalla de inicio de sesión.', max_length=100, verbose_name='Encabezado del login')),
                ('site_brand', models.CharField(default='Agricola de la Costa', help_text='Nombre corto que aparece junto al logo en la barra lateral.', max_length=60, verbose_name='Nombre en barra lateral')),
                ('company_logo', models.ImageField(blank=True, help_text='PNG o SVG con fondo transparente. Recomendado ≥ 200 × 60 px.', null=True, upload_to='site/', verbose_name='Logo de la empresa')),
                ('navigation_expanded', models.BooleanField(default=False, help_text='Muestra todas las secciones del menú lateral abiertas al cargar la página.', verbose_name='Sidebar expandido al entrar')),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
                'verbose_name_plural': 'Configuración del Sitio',
            },
        ),
    ]
