# Generated by Django 5.2.4 on 2026-04-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0004_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='custom_topbar_css',
            field=models.TextField(blank=True, help_text='CSS personalizado que se aplicará a la barra de navegación superior del admin.', verbose_name='CSS personalizado para la barra superior'),
        ),
    ]
