# Generated by Django 5.2.4 on 2026-04-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0005_siteconfiguration_custom_topbar_css'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='show_ui_builder',
            field=models.BooleanField(default=False, help_text='Muestra el panel de personalización de tema (UI Builder) en la barra lateral del admin. Recomendado solo para administradores durante configuración inicial.', verbose_name='Habilitar selector de temas Jazzmin'),
        ),
    ]
