[tool.poetry]
<<<<<<< HEAD
name = "django-system"
version = "0.1.0"
description = ""
authors = ["bitboy"]
=======
name = "app"
version = "0.1.0"
description = "sistema de ventas y gastos"
authors = ["luis corrales"]
>>>>>>> e36d22bf634f764dffac4100fb5b4d24b0dd40b7
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
<<<<<<< HEAD
python-dotenv = "^1.0.1"
mysqlclient = "^2.2.5"
django-jazzmin = "^3.0.1"
django-import-export = "^4.2.0"
django-compressor = "^4.5.1"
=======
django = "^5.1.2"
django-compressor = "^4.5.1"
django-jazzmin = "^3.0.1"
mysqlclient = "^2.2.5"
python-dotenv = "^1.0.1"
django-import-export = "^4.1.1"
>>>>>>> e36d22bf634f764dffac4100fb5b4d24b0dd40b7


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
<<<<<<< HEAD

[virtualenvs]
create = true
in-project = true
=======
>>>>>>> e36d22bf634f764dffac4100fb5b4d24b0dd40b7
