[tool.poetry]
name = "app"
version = "0.1.0"
description = "sistema de ventas y gastos"
authors = ["luis corrales"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.1.2"
django-compressor = "^4.5.1"
django-jazzmin = "^3.0.1"
mysqlclient = "^2.2.5"
python-dotenv = "^1.0.1"
django-import-export = "^4.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
