# Generated by Django 5.0.6 on 2024-07-31 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registro",
            name="id_cat_gastos",
        ),
        migrations.RemoveField(
            model_name="registro",
            name="id_sucursal",
        ),
        migrations.RenameField(
            model_name="productor",
            old_name="phone",
            new_name="clabe_interbancaria",
        ),
        migrations.RenameField(
            model_name="productor",
            old_name="fullname",
            new_name="nombre_completo",
        ),
        migrations.RemoveField(
            model_name="productor",
            name="email",
        ),
        migrations.RemoveField(
            model_name="productor",
            name="id_estado",
        ),
        migrations.AddField(
            model_name="productor",
            name="correo",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="productor",
            name="id_sucursal",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogo.sucursal",
            ),
        ),
        migrations.AddField(
            model_name="productor",
            name="num_cuenta",
            field=models.CharField(default="0000000000", max_length=20),
        ),
        migrations.AddField(
            model_name="productor",
            name="telefono",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="sucursal",
            name="direccion",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="sucursal",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="sucursal",
            name="telefono",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name="CatGastos",
        ),
        migrations.DeleteModel(
            name="Registro",
        ),
    ]
