# Generated by Django 5.0.6 on 2024-08-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0002_remove_registro_id_cat_gastos_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productor",
            name="clabe_interbancaria",
            field=models.CharField(default="000000000000000000", max_length=20),
        ),
        migrations.AlterField(
            model_name="productor",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="sucursal",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
