# Generated by Django 5.0.6 on 2024-08-01 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0003_alter_productor_clabe_interbancaria_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="estado",
            options={"ordering": ["nombre"], "verbose_name_plural": "Estados"},
        ),
        migrations.AlterModelOptions(
            name="productor",
            options={
                "ordering": ["nombre_completo"],
                "verbose_name_plural": "Productores",
            },
        ),
        migrations.AlterModelOptions(
            name="sucursal",
            options={"ordering": ["nombre"], "verbose_name_plural": "Sucursales"},
        ),
    ]
