# Generated by Django 5.0.6 on 2024-08-01 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0004_alter_estado_options_alter_productor_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="estado",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Estado",
                "verbose_name_plural": "Estados",
            },
        ),
        migrations.AlterModelOptions(
            name="productor",
            options={
                "ordering": ["nombre_completo"],
                "verbose_name": "Productor",
                "verbose_name_plural": "Productores",
            },
        ),
        migrations.AlterModelOptions(
            name="sucursal",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Sucursal",
                "verbose_name_plural": "Sucursales",
            },
        ),
    ]
