# Generated by Django 5.0.6 on 2024-08-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0005_alter_estado_options_alter_productor_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("siglas", models.CharField(max_length=10)),
                ("nombre", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "Paises",
                "ordering": ["siglas"],
            },
        ),
    ]
