# Generated by Django 5.1.3 on 2025-01-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_rename_precio_producto_precio_unitario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='catalogo/productos/', verbose_name='Imagen del Producto'),
        ),
        migrations.AddField(
            model_name='productor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productores/imagenes/', verbose_name='Imagen del Productor'),
        ),
    ]
