# Generated by Django 5.1.3 on 2025-01-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_alter_producto_precio_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default='Mango', max_length=100),
        ),
    ]
