# Generated by Django 5.1.3 on 2025-01-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_alter_producto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productor',
            name='imagen',
            field=models.ImageField(blank=True, default='productores/imagenes/default.svg', null=True, upload_to='productores/imagenes/', verbose_name='Imagen del Productor'),
        ),
    ]
