# Generated by Django 5.1.3 on 2025-01-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0014_alter_productor_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ['siglas'], 'verbose_name': 'Pais', 'verbose_name_plural': 'Paises'},
        ),
        migrations.AddField(
            model_name='pais',
            name='bandera',
            field=models.ImageField(blank=True, null=True, upload_to='paises/banderas/', verbose_name='Bandera del País'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Subir imagen con formato .jpg, .jpeg o .png', null=True, upload_to='catalogo/productos/', verbose_name='Imagen del Producto'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='imagen',
            field=models.ImageField(blank=True, default='productores/imagenes/default.svg', help_text='Subir imagen con formato .jpg, .jpeg o .png', null=True, upload_to='productores/imagenes/', verbose_name='Imagen del Productor'),
        ),
    ]
