# Generated by Django 5.1.3 on 2025-01-11 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0015_alter_pais_options_pais_bandera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='pais',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.pais'),
        ),
    ]
