# Generated by Django 5.0.6 on 2024-08-03 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0002_alter_cliente_pais_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ventas",
            name="pedimento",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ventas",
            name="PO",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ventas",
            name="agente_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ventas.agente",
                verbose_name="Agente aduanal",
            ),
        ),
        migrations.AlterField(
            model_name="ventas",
            name="descripcion",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
