# Generated by Django 5.1.3 on 2024-11-12 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_ventas_pedimento_alter_ventas_po_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventas',
            old_name='caja',
            new_name='cantidad',
        ),
    ]
