# Generated by Django 5.1.3 on 2024-12-30 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_pais_moneda'),
        ('ventas', '0007_anticipo_estado_anticipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agente',
            options={'verbose_name': 'Agente aduanal', 'verbose_name_plural': 'Agentes aduanales'},
        ),
        migrations.AlterModelOptions(
            name='anticipo',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Anticipo', 'verbose_name_plural': 'Anticipos'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='ventas',
            options={'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.RenameField(
            model_name='agente',
            old_name='fecha',
            new_name='fecha_registro',
        ),
        migrations.AddField(
            model_name='agente',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='agente',
            name='pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogo.pais'),
        ),
        migrations.AddField(
            model_name='agente',
            name='telefono',
            field=models.CharField(blank=True, default='Sin teléfono', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='tipo_venta',
            field=models.CharField(choices=[('Nacional', 'Nacional'), ('Exportación', 'Exportacion')], max_length=50),
        ),
    ]
