# Generated by Django 5.1.3 on 2025-01-10 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_producto'),
        ('gastos', '0017_alter_compra_producto'),
        ('ventas', '0008_alter_agente_options_alter_anticipo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto'),
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
