# Generated by Django 5.1.3 on 2025-01-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_cliente_direccion_alter_anticipo_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='imagen',
            field=models.ImageField(blank=True, default='clientes/default.jpg', null=True, upload_to='clientes'),
        ),
    ]
