# Generated by Django 5.1.3 on 2025-01-11 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_cliente_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, default='Desconocida', max_length=250, null=True),
        ),
    ]
