# Generated by Django 5.1.3 on 2025-01-12 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0014_alter_cliente_pais_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='pais_id',
            new_name='pais',
        ),
    ]
