# Generated by Django 5.1.3 on 2025-01-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0015_rename_pais_id_cliente_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='imagen',
            field=models.ImageField(blank=True, default='clientes/default.png', null=True, upload_to='clientes'),
        ),
    ]
