# Generated by Django 5.2.4 on 2025-12-03 13:30

import django.core.validators
import django.db.models.deletion
import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0016_estado_pais'),
        ('gastos', '0023_alter_saldomensual_mes'),
        ('ventas', '0018_anticipo_monto_currency_ventas_monto_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Net 30, Net 60, etc.', max_length=100)),
                ('dias_credito', models.PositiveIntegerField(help_text='Número de días para el crédito (1-365)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('tasa_interes_mensual', models.DecimalField(decimal_places=4, default=0.0, help_text='Tasa de interés mensual (decimal, ej: 0.0200 = 2%)', max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Término de Crédito',
                'verbose_name_plural': 'Términos de Crédito',
                'ordering': ['dias_credito'],
            },
        ),
        migrations.AlterModelOptions(
            name='ventas',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='calificacion_credito',
            field=models.CharField(choices=[('A+', 'Excelente'), ('A', 'Bueno'), ('B', 'Regular'), ('C', 'Riesgoso')], default='A', help_text='Calificación crediticia del cliente', max_length=2),
        ),
        migrations.AddField(
            model_name='cliente',
            name='limite_credito',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='cliente',
            name='limite_credito_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('AUD', 'Dólar Australiano (AUD)'), ('CAD', 'Dólar Canadiense (CAD)'), ('USD', 'Dólar Estadounidense (USD)'), ('EUR', 'Euro (EUR)'), ('CHF', 'Franco Suizo (CHF)'), ('GBP', 'Libra Esterlina (GBP)'), ('MXN', 'Peso Mexicano (MXN)'), ('INR', 'Rupia India (INR)'), ('JPY', 'Yen Japonés (JPY)'), ('CNY', 'Yuan Chino (CNY)')], default='MXN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('Contado', 'Solo Contado'), ('Credito', 'Solo Crédito'), ('Mixto', 'Contado y Crédito')], default='Contado', max_length=10),
        ),
        migrations.AddField(
            model_name='ventas',
            name='estado_cobranza',
            field=models.CharField(choices=[('Pagado', 'Pagado'), ('Pendiente', 'Pendiente'), ('Parcial', 'Parcialmente Pagado'), ('Vencido', 'Vencido'), ('Incobrable', 'Incobrable')], default='Pagado', max_length=15),
        ),
        migrations.AddField(
            model_name='ventas',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Fecha de vencimiento para ventas a crédito', null=True),
        ),
        migrations.AddField(
            model_name='ventas',
            name='incoterm',
            field=models.CharField(blank=True, help_text='Términos internacionales de comercio (FOB, CIF, etc.)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ventas',
            name='modalidad_pago',
            field=models.CharField(choices=[('Contado', 'Contado'), ('Credito', 'Crédito')], default='Contado', max_length=10),
        ),
        migrations.AddField(
            model_name='ventas',
            name='moneda_venta',
            field=models.CharField(default='MXN', help_text='Moneda en la que se realizó la venta', max_length=3),
        ),
        migrations.AddField(
            model_name='ventas',
            name='monto_pagado',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), help_text='Monto total pagado hasta la fecha', max_digits=12),
        ),
        migrations.AddField(
            model_name='ventas',
            name='monto_pagado_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('AUD', 'Dólar Australiano (AUD)'), ('CAD', 'Dólar Canadiense (CAD)'), ('USD', 'Dólar Estadounidense (USD)'), ('EUR', 'Euro (EUR)'), ('CHF', 'Franco Suizo (CHF)'), ('GBP', 'Libra Esterlina (GBP)'), ('MXN', 'Peso Mexicano (MXN)'), ('INR', 'Rupia India (INR)'), ('JPY', 'Yen Japonés (JPY)'), ('CNY', 'Yuan Chino (CNY)')], default='MXN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='ventas',
            name='tipo_cambio',
            field=models.DecimalField(decimal_places=4, default=1.0, help_text='Tipo de cambio aplicado al momento de la venta', max_digits=10),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='monto',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12),
        ),
        migrations.CreateModel(
            name='MercadoDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Nacional, USA, Canadá, Europa', max_length=100)),
                ('requiere_documentacion_especial', models.BooleanField(default=False)),
                ('moneda_preferida', models.CharField(default='USD', help_text='Código de moneda ISO', max_length=3)),
                ('factor_riesgo', models.DecimalField(decimal_places=2, default=1.0, help_text='Factor de riesgo (1.0 = normal, >1.0 = mayor riesgo)', max_digits=3, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(5.0)])),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('paises', models.ManyToManyField(help_text='Países que pertenecen a este mercado', to='catalogo.pais')),
            ],
            options={
                'verbose_name': 'Mercado de Destino',
                'verbose_name_plural': 'Mercados de Destino',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='mercado_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.mercadodestino'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='mercado_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.mercadodestino'),
        ),
        migrations.CreateModel(
            name='PagoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('monto_pago_currency', djmoney.models.fields.CurrencyField(choices=[('AUD', 'Dólar Australiano (AUD)'), ('CAD', 'Dólar Canadiense (CAD)'), ('USD', 'Dólar Estadounidense (USD)'), ('EUR', 'Euro (EUR)'), ('CHF', 'Franco Suizo (CHF)'), ('GBP', 'Libra Esterlina (GBP)'), ('MXN', 'Peso Mexicano (MXN)'), ('INR', 'Rupia India (INR)'), ('JPY', 'Yen Japonés (JPY)'), ('CNY', 'Yuan Chino (CNY)')], default='MXN', editable=False, max_length=3)),
                ('monto_pago', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia Bancaria'), ('Cheque', 'Cheque'), ('Tarjeta', 'Tarjeta de Crédito/Débito')], max_length=15)),
                ('referencia', models.CharField(blank=True, help_text='Número de referencia o cheque', max_length=100, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cuenta_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastos.cuenta')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ventas.ventas')),
            ],
            options={
                'verbose_name': 'Pago de Venta',
                'verbose_name_plural': 'Pagos de Ventas',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='termino_credito_predeterminado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.terminocredito'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='termino_credito',
            field=models.ForeignKey(blank=True, help_text='Solo requerido para ventas a crédito', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.terminocredito'),
        ),
        migrations.AddIndex(
            model_name='ventas',
            index=models.Index(fields=['modalidad_pago', 'estado_cobranza'], name='ventas_vent_modalid_6ef65f_idx'),
        ),
        migrations.AddIndex(
            model_name='ventas',
            index=models.Index(fields=['fecha_vencimiento'], name='ventas_vent_fecha_v_7986fc_idx'),
        ),
        migrations.AddIndex(
            model_name='ventas',
            index=models.Index(fields=['cliente', 'estado_cobranza'], name='ventas_vent_cliente_6e0213_idx'),
        ),
    ]
