# Generated by Django 5.2.4 on 2026-03-12 08:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0019_terminocredito_alter_ventas_options_cliente_activo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCuentasPorCobrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_corriente', models.PositiveIntegerField(default=30, help_text="Días máximos para considerar saldo como 'Corriente'")),
                ('dias_vencido_1', models.PositiveIntegerField(default=60, help_text="Días máximos para 'Vencido 1' (31-60 días)")),
                ('dias_vencido_2', models.PositiveIntegerField(default=90, help_text="Días máximos para 'Vencido 2' (61-90 días)")),
                ('calculo_automatico_aging', models.BooleanField(default=True, help_text='Activar cálculo automático diario de aging')),
                ('hora_calculo_aging', models.TimeField(default='02:00:00', help_text='Hora del día para ejecutar cálculo automático')),
                ('frecuencia_calculo', models.CharField(choices=[('DIARIO', 'Diario'), ('SEMANAL', 'Semanal')], default='DIARIO', help_text='Frecuencia para cálculo automático de aging', max_length=10)),
                ('enviar_alertas_vencimiento', models.BooleanField(default=True, help_text='Enviar alertas automáticas por vencimientos próximos')),
                ('dias_previos_alerta', models.PositiveIntegerField(default=5, help_text='Días antes del vencimiento para enviar alerta')),
                ('email_responsable_cobranza', models.EmailField(blank=True, help_text='Email del responsable de cobranza para recibir alertas', max_length=254)),
                ('permitir_sobregiro_credito', models.BooleanField(default=False, help_text='Permitir ventas que excedan límite de crédito (con autorización)')),
                ('porcentaje_sobregiro_permitido', models.FloatField(default=10.0, help_text='Porcentaje máximo de sobregiro permitido sobre límite de crédito', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Cuentas por Cobrar',
                'verbose_name_plural': 'Configuraciones de Cuentas por Cobrar',
                'db_table': 'ventas_configuracion_cxc',
            },
        ),
        migrations.CreateModel(
            name='AntigüedadSaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_calculo', models.DateField(default=django.utils.timezone.now, help_text='Fecha en que se calculó este aging')),
                ('corriente_currency', djmoney.models.fields.CurrencyField(choices=[('AUD', 'Dólar Australiano (AUD)'), ('CAD', 'Dólar Canadiense (CAD)'), ('USD', 'Dólar Estadounidense (USD)'), ('EUR', 'Euro (EUR)'), ('CHF', 'Franco Suizo (CHF)'), ('GBP', 'Libra Esterlina (GBP)'), ('MXN', 'Peso Mexicano (MXN)'), ('INR', 'Rupia India (INR)'), ('JPY', 'Yen Japonés (JPY)'), ('CNY', 'Yuan Chino (CNY)')], default='MXN', editable=False, max_length=3)),
                ('corriente', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), help_text='Saldos 0-30 días desde vencimiento', max_digits=12)),
                ('vencido_1_currency', djmoney.models.fields.CurrencyField(choices=[('AUD', 'Dólar Australiano (AUD)'), ('CAD', 'Dólar Canadiense (CAD)'), ('USD', 'Dólar Estadounidense (USD)'), ('EUR', 'Euro (EUR)'), ('CHF', 'Franco Suizo (CHF)'), ('GBP', 'Libra Esterlina (GBP)'), ('MXN', 'Peso Mexicano (MXN)'), ('INR', 'Rupia India (INR)'), ('JPY', 'Yen Japonés (JPY)'), ('CNY', 'Yuan Chino (CNY)')], default='MXN', editable=False, max_length=3)),
                ('vencido_1', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), help_text='Saldos 31-60 días vencidos', max_digits=12)),
                ('vencido_2_currency', djmoney.models.fields.CurrencyField(choices=[('AUD', 'Dólar Australiano (AUD)'), ('CAD', 'Dólar Canadiense (CAD)'), ('USD', 'Dólar Estadounidense (USD)'), ('EUR', 'Euro (EUR)'), ('CHF', 'Franco Suizo (CHF)'), ('GBP', 'Libra Esterlina (GBP)'), ('MXN', 'Peso Mexicano (MXN)'), ('INR', 'Rupia India (INR)'), ('JPY', 'Yen Japonés (JPY)'), ('CNY', 'Yuan Chino (CNY)')], default='MXN', editable=False, max_length=3)),
                ('vencido_2', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), help_text='Saldos 61-90 días vencidos', max_digits=12)),
                ('vencido_3_currency', djmoney.models.fields.CurrencyField(choices=[('AUD', 'Dólar Australiano (AUD)'), ('CAD', 'Dólar Canadiense (CAD)'), ('USD', 'Dólar Estadounidense (USD)'), ('EUR', 'Euro (EUR)'), ('CHF', 'Franco Suizo (CHF)'), ('GBP', 'Libra Esterlina (GBP)'), ('MXN', 'Peso Mexicano (MXN)'), ('INR', 'Rupia India (INR)'), ('JPY', 'Yen Japonés (JPY)'), ('CNY', 'Yuan Chino (CNY)')], default='MXN', editable=False, max_length=3)),
                ('vencido_3', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), help_text='Saldos +90 días vencidos (morosos críticos)', max_digits=12)),
                ('total_saldo_currency', djmoney.models.fields.CurrencyField(choices=[('AUD', 'Dólar Australiano (AUD)'), ('CAD', 'Dólar Canadiense (CAD)'), ('USD', 'Dólar Estadounidense (USD)'), ('EUR', 'Euro (EUR)'), ('CHF', 'Franco Suizo (CHF)'), ('GBP', 'Libra Esterlina (GBP)'), ('MXN', 'Peso Mexicano (MXN)'), ('INR', 'Rupia India (INR)'), ('JPY', 'Yen Japonés (JPY)'), ('CNY', 'Yuan Chino (CNY)')], default='MXN', editable=False, max_length=3)),
                ('total_saldo', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), help_text='Total de saldos pendientes', max_digits=12)),
                ('numero_facturas', models.PositiveIntegerField(default=0, help_text='Cantidad de facturas pendientes')),
                ('promedio_dias_pago', models.FloatField(blank=True, help_text='Promedio histórico de días para pago completo', null=True)),
                ('moneda', models.CharField(default='MXN', help_text='Moneda base para los cálculos', max_length=3)),
                ('calculado_por', models.CharField(default='Sistema', help_text='Sistema o usuario que ejecutó el cálculo', max_length=100)),
                ('cliente', models.ForeignKey(help_text='Cliente analizado', on_delete=django.db.models.deletion.CASCADE, related_name='historico_aging', to='ventas.cliente')),
            ],
            options={
                'verbose_name': 'Análisis de Antigüedad',
                'verbose_name_plural': 'Análisis de Antigüedad de Saldos',
                'db_table': 'ventas_antiguedad_saldo',
                'ordering': ['-fecha_calculo', '-total_saldo'],
                'indexes': [models.Index(fields=['fecha_calculo'], name='ventas_anti_fecha_c_54f151_idx'), models.Index(fields=['cliente', 'fecha_calculo'], name='ventas_anti_cliente_985b6d_idx'), models.Index(fields=['fecha_calculo', 'total_saldo'], name='ventas_anti_fecha_c_da1f60_idx')],
                'unique_together': {('cliente', 'fecha_calculo')},
            },
        ),
        migrations.CreateModel(
            name='EstadoCuentaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, help_text='Momento en que se generó el reporte')),
                ('periodo_inicio', models.DateField(help_text='Fecha de inicio del período analizado')),
                ('periodo_fin', models.DateField(help_text='Fecha de fin del período analizado')),
                ('total_ventas_currency', djmoney.models.fields.CurrencyField(choices=[('AUD', 'Dólar Australiano (AUD)'), ('CAD', 'Dólar Canadiense (CAD)'), ('USD', 'Dólar Estadounidense (USD)'), ('EUR', 'Euro (EUR)'), ('CHF', 'Franco Suizo (CHF)'), ('GBP', 'Libra Esterlina (GBP)'), ('MXN', 'Peso Mexicano (MXN)'), ('INR', 'Rupia India (INR)'), ('JPY', 'Yen Japonés (JPY)'), ('CNY', 'Yuan Chino (CNY)')], default='MXN', editable=False, max_length=3)),
                ('total_ventas', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), help_text='Total de ventas a crédito en el período', max_digits=12)),
                ('total_abonos_currency', djmoney.models.fields.CurrencyField(choices=[('AUD', 'Dólar Australiano (AUD)'), ('CAD', 'Dólar Canadiense (CAD)'), ('USD', 'Dólar Estadounidense (USD)'), ('EUR', 'Euro (EUR)'), ('CHF', 'Franco Suizo (CHF)'), ('GBP', 'Libra Esterlina (GBP)'), ('MXN', 'Peso Mexicano (MXN)'), ('INR', 'Rupia India (INR)'), ('JPY', 'Yen Japonés (JPY)'), ('CNY', 'Yuan Chino (CNY)')], default='MXN', editable=False, max_length=3)),
                ('total_abonos', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), help_text='Total de abonos/pagos recibidos en el período', max_digits=12)),
                ('saldo_final_currency', djmoney.models.fields.CurrencyField(choices=[('AUD', 'Dólar Australiano (AUD)'), ('CAD', 'Dólar Canadiense (CAD)'), ('USD', 'Dólar Estadounidense (USD)'), ('EUR', 'Euro (EUR)'), ('CHF', 'Franco Suizo (CHF)'), ('GBP', 'Libra Esterlina (GBP)'), ('MXN', 'Peso Mexicano (MXN)'), ('INR', 'Rupia India (INR)'), ('JPY', 'Yen Japonés (JPY)'), ('CNY', 'Yuan Chino (CNY)')], default='MXN', editable=False, max_length=3)),
                ('saldo_final', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), help_text='Saldo pendiente al final del período (Ventas - Abonos)', max_digits=12)),
                ('numero_facturas', models.PositiveIntegerField(default=0, help_text='Cantidad de facturas incluidas en el período')),
                ('formato_generado', models.CharField(choices=[('WEB', 'Vista Web'), ('PDF', 'Documento PDF'), ('EXCEL', 'Hoja de Excel')], default='WEB', help_text='Formato en que se generó el estado de cuenta', max_length=10)),
                ('archivo_generado', models.FileField(blank=True, help_text='Archivo generado (PDF o Excel) si aplica', null=True, upload_to='estados_cuenta/%Y/%m/')),
                ('generado_por', models.CharField(help_text='Usuario que generó el estado de cuenta', max_length=150)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el estado de cuenta')),
                ('cliente', models.ForeignKey(help_text='Cliente del estado de cuenta', on_delete=django.db.models.deletion.CASCADE, related_name='estados_cuenta', to='ventas.cliente')),
            ],
            options={
                'verbose_name': 'Estado de Cuenta',
                'verbose_name_plural': 'Estados de Cuenta de Clientes',
                'db_table': 'ventas_estado_cuenta_cliente',
                'ordering': ['-fecha_generacion'],
                'indexes': [models.Index(fields=['cliente', 'fecha_generacion'], name='ventas_esta_cliente_6d702b_idx'), models.Index(fields=['periodo_inicio', 'periodo_fin'], name='ventas_esta_periodo_3c1a58_idx'), models.Index(fields=['fecha_generacion'], name='ventas_esta_fecha_g_541c0a_idx')],
            },
        ),
        migrations.CreateModel(
            name='SaldoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_original_currency', djmoney.models.fields.CurrencyField(choices=[('AUD', 'Dólar Australiano (AUD)'), ('CAD', 'Dólar Canadiense (CAD)'), ('USD', 'Dólar Estadounidense (USD)'), ('EUR', 'Euro (EUR)'), ('CHF', 'Franco Suizo (CHF)'), ('GBP', 'Libra Esterlina (GBP)'), ('MXN', 'Peso Mexicano (MXN)'), ('INR', 'Rupia India (INR)'), ('JPY', 'Yen Japonés (JPY)'), ('CNY', 'Yuan Chino (CNY)')], default='MXN', editable=False, max_length=3)),
                ('monto_original', djmoney.models.fields.MoneyField(decimal_places=2, help_text='Monto original de la venta a crédito', max_digits=12)),
                ('saldo_pendiente_currency', djmoney.models.fields.CurrencyField(choices=[('AUD', 'Dólar Australiano (AUD)'), ('CAD', 'Dólar Canadiense (CAD)'), ('USD', 'Dólar Estadounidense (USD)'), ('EUR', 'Euro (EUR)'), ('CHF', 'Franco Suizo (CHF)'), ('GBP', 'Libra Esterlina (GBP)'), ('MXN', 'Peso Mexicano (MXN)'), ('INR', 'Rupia India (INR)'), ('JPY', 'Yen Japonés (JPY)'), ('CNY', 'Yuan Chino (CNY)')], default='MXN', editable=False, max_length=3)),
                ('saldo_pendiente', djmoney.models.fields.MoneyField(decimal_places=2, help_text='Saldo actual después de abonos', max_digits=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Momento en que se registró la deuda')),
                ('fecha_vencimiento', models.DateField(help_text='Fecha límite para pago sin intereses')),
                ('fecha_ultimo_pago', models.DateTimeField(blank=True, help_text='Fecha del último pago registrado', null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Parcial'), ('PAGADO', 'Pagado'), ('VENCIDO', 'Vencido'), ('INCOBRABLE', 'Incobrable')], default='PENDIENTE', help_text='Estado actual del saldo', max_length=20)),
                ('moneda', models.CharField(default='MXN', help_text='Moneda del saldo (MXN, USD, etc.)', max_length=3)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el saldo o gestiones de cobranza')),
                ('cliente', models.ForeignKey(help_text='Cliente asociado al saldo', on_delete=django.db.models.deletion.PROTECT, related_name='saldos_cxc', to='ventas.cliente')),
                ('venta', models.OneToOneField(help_text='Venta que origina este saldo', on_delete=django.db.models.deletion.PROTECT, related_name='saldo_cxc', to='ventas.ventas')),
            ],
            options={
                'verbose_name': 'Saldo por Cobrar',
                'verbose_name_plural': 'Saldos por Cobrar',
                'db_table': 'ventas_saldo_cliente',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['cliente', 'estado'], name='ventas_sald_cliente_14957b_idx'), models.Index(fields=['fecha_vencimiento'], name='ventas_sald_fecha_v_17844c_idx'), models.Index(fields=['estado', 'fecha_vencimiento'], name='ventas_sald_estado_914bcc_idx'), models.Index(fields=['cliente', 'fecha_creacion'], name='ventas_sald_cliente_9e78c2_idx')],
            },
        ),
    ]
