# Generated by Django 5.2.4 on 2026-04-01 09:37

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0020_configuracioncuentasporcobrar_antigüedadsaldo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObligacionFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(help_text='Ej: Semestre Julio-Diciembre 2025', max_length=100)),
                ('isr_ingresos_propios_currency', djmoney.models.fields.CurrencyField(choices=[('AUD', 'Dólar Australiano (AUD)'), ('CAD', 'Dólar Canadiense (CAD)'), ('USD', 'Dólar Estadounidense (USD)'), ('EUR', 'Euro (EUR)'), ('CHF', 'Franco Suizo (CHF)'), ('GBP', 'Libra Esterlina (GBP)'), ('MXN', 'Peso Mexicano (MXN)'), ('INR', 'Rupia India (INR)'), ('JPY', 'Yen Japonés (JPY)'), ('CNY', 'Yuan Chino (CNY)')], default='MXN', editable=False, max_length=3)),
                ('isr_ingresos_propios', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), help_text='ISR Ingresos Propios', max_digits=14)),
                ('isr_resico_currency', djmoney.models.fields.CurrencyField(choices=[('AUD', 'Dólar Australiano (AUD)'), ('CAD', 'Dólar Canadiense (CAD)'), ('USD', 'Dólar Estadounidense (USD)'), ('EUR', 'Euro (EUR)'), ('CHF', 'Franco Suizo (CHF)'), ('GBP', 'Libra Esterlina (GBP)'), ('MXN', 'Peso Mexicano (MXN)'), ('INR', 'Rupia India (INR)'), ('JPY', 'Yen Japonés (JPY)'), ('CNY', 'Yuan Chino (CNY)')], default='MXN', editable=False, max_length=3)),
                ('isr_resico', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), help_text='ISR RESICO Servicios Profesionales', max_digits=14)),
                ('isr_retenciones_salarios_currency', djmoney.models.fields.CurrencyField(choices=[('AUD', 'Dólar Australiano (AUD)'), ('CAD', 'Dólar Canadiense (CAD)'), ('USD', 'Dólar Estadounidense (USD)'), ('EUR', 'Euro (EUR)'), ('CHF', 'Franco Suizo (CHF)'), ('GBP', 'Libra Esterlina (GBP)'), ('MXN', 'Peso Mexicano (MXN)'), ('INR', 'Rupia India (INR)'), ('JPY', 'Yen Japonés (JPY)'), ('CNY', 'Yuan Chino (CNY)')], default='MXN', editable=False, max_length=3)),
                ('isr_retenciones_salarios', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), help_text='ISR Retenciones por Salarios', max_digits=14)),
                ('iva_retenciones_profesionales_currency', djmoney.models.fields.CurrencyField(choices=[('AUD', 'Dólar Australiano (AUD)'), ('CAD', 'Dólar Canadiense (CAD)'), ('USD', 'Dólar Estadounidense (USD)'), ('EUR', 'Euro (EUR)'), ('CHF', 'Franco Suizo (CHF)'), ('GBP', 'Libra Esterlina (GBP)'), ('MXN', 'Peso Mexicano (MXN)'), ('INR', 'Rupia India (INR)'), ('JPY', 'Yen Japonés (JPY)'), ('CNY', 'Yuan Chino (CNY)')], default='MXN', editable=False, max_length=3)),
                ('iva_retenciones_profesionales', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), help_text='IVA Retenciones Servicios Profesionales', max_digits=14)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Obligación Fiscal',
                'verbose_name_plural': 'Obligaciones Fiscales',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.AddField(
            model_name='ventas',
            name='tipo_registro',
            field=models.CharField(choices=[('VENTA', 'Venta'), ('MAQUILA', 'Maquila')], default='VENTA', help_text='Tipo de registro: Venta normal o Maquila', max_length=10),
        ),
    ]
