# Generated by Django 5.2.4 on 2026-04-04 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0021_ventas_tipo_registro_obligacionfiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncuentasporcobrar',
            name='tipo_cambio_usd',
            field=models.DecimalField(decimal_places=4, default=17.0, help_text='Tipo de cambio USD→MXN vigente (actualizar manualmente cada día)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0001)]),
        ),
    ]
