# Generated by Django 5.2.4 on 2026-04-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0022_add_tipo_cambio_usd_to_configuracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='anticipo',
            name='folio_factura_anticipo',
            field=models.CharField(blank=True, help_text='Folio del CFDI de anticipo (ej: B 1980)', max_length=50, null=True, verbose_name='Folio factura anticipo'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='ajuste',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ajuste positivo (cargo) o negativo (descuento)', max_digits=12, verbose_name='Ajuste'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='cfdi_cancelado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CFDIs cancelados'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='fecha_emision_cfdi',
            field=models.DateField(blank=True, help_text='Fecha de emisión del CFDI de exportación', null=True, verbose_name='Fecha emisión CFDI'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='folio_factura',
            field=models.CharField(blank=True, help_text='Folio del CFDI (ej: B 1996)', max_length=50, null=True, verbose_name='Folio factura'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='nota_cargo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nota de cargo'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='nota_credito',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nota de crédito'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='numero_carga_comprador',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Carga comprador (PANORAMA LOAD)'),
        ),
    ]
