# Generated by Django 5.2.4 on 2026-04-10 21:38

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def clean_cantidad_values(apps, schema_editor):
    """
    Limpia valores no numéricos del campo cantidad antes de convertirlo a DECIMAL.
    Extrae solo los dígitos y el punto/coma decimal; convierte comas a puntos.
    Registros que no contengan ningún número se establecen en 0.001 (mínimo válido).
    """
    import re
    Ventas = apps.get_model('ventas', 'Ventas')
    db_alias = schema_editor.connection.alias

    for venta in Ventas.objects.using(db_alias).all():
        raw = str(venta.cantidad or '')
        # Extraer primer número (con comas o puntos) del string
        match = re.search(r'[\d]+(?:[,\.][\d]+)*', raw)
        if match:
            num_str = match.group(0).replace(',', '.')
            try:
                value = Decimal(num_str)
                venta.cantidad = value if value > 0 else Decimal('0.001')
            except Exception:
                venta.cantidad = Decimal('0.001')
        else:
            venta.cantidad = Decimal('0.001')
        venta.save(update_fields=['cantidad'])


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0023_add_campos_fiscales_y_sync_saldo'),
    ]

    operations = [
        # Paso 1: limpiar datos existentes (RunPython actúa sobre CharField aún)
        migrations.RunPython(clean_cantidad_values, migrations.RunPython.noop),
        # Paso 2: alterar el tipo de columna a DECIMAL
        migrations.AlterField(
            model_name='ventas',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, help_text='Cantidad vendida (ej: 1500.000 kg)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
    ]
