# Generated by Django 5.2.4 on 2026-04-13 15:39

import django.core.validators
import django.db.models.deletion
import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0016_estado_pais'),
        ('gastos', '0024_alter_saldomensual_año_alter_saldomensual_mes'),
        ('ventas', '0025_banking_controls'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagoventa',
            options={'ordering': ['-fecha_pago', '-fecha_registro'], 'verbose_name': 'Pago de Venta', 'verbose_name_plural': 'Pagos de Ventas'},
        ),
        migrations.RemoveIndex(
            model_name='pagoventa',
            name='ventas_pago_proceso_idx',
        ),
        migrations.RenameIndex(
            model_name='anticipo',
            new_name='ventas_anti_cliente_00a571_idx',
            old_name='ventas_anti_cliente_estado_idx',
        ),
        migrations.RenameIndex(
            model_name='anticipo',
            new_name='ventas_anti_estado__68f417_idx',
            old_name='ventas_anti_estado_idx',
        ),
        migrations.RenameIndex(
            model_name='pagoventa',
            new_name='ventas_pago_venta_i_6d2b2a_idx',
            old_name='ventas_pago_venta_fecha_idx',
        ),
        migrations.RemoveField(
            model_name='pagoventa',
            name='procesado',
        ),
        migrations.AddField(
            model_name='pagoventa',
            name='comprobante_pago',
            field=models.FileField(blank=True, help_text='Comprobante de pago (imagen o PDF)', null=True, upload_to='comprobantes_pagos/%Y/%m/', verbose_name='Comprobante de Pago'),
        ),
        migrations.AlterField(
            model_name='anticipo',
            name='estado_anticipo',
            field=models.CharField(choices=[('Pendiente', 'Pendiente de Aplicar'), ('Aplicado', 'Aplicado a Venta'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='anticipo',
            name='monto',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='pagoventa',
            name='monto_pago',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='pagoventa',
            name='referencia',
            field=models.CharField(blank=True, help_text='Número de referencia, cheque o ID de transacción', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pagoventa',
            name='venta',
            field=models.ForeignKey(help_text='Venta a la que pertenece este pago (relación 1:N)', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ventas.ventas'),
        ),
        migrations.AddIndex(
            model_name='anticipo',
            index=models.Index(fields=['fecha'], name='ventas_anti_fecha_da1872_idx'),
        ),
        migrations.AddIndex(
            model_name='pagoventa',
            index=models.Index(fields=['fecha_pago'], name='ventas_pago_fecha_p_150855_idx'),
        ),
    ]
