# Generated by Django 5.2.4 on 2026-04-13 19:15

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0026_alter_pagoventa_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anticipo',
            name='monto',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pagoventa',
            name='monto_pago',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12),
        ),
    ]
