# Generated by Django 5.2.4 on 2026-04-14 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0027_alter_anticipo_monto_alter_pagoventa_monto_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anticipo',
            name='sucursal',
        ),
    ]
