# Generated by Django 5.2.4 on 2026-04-29

import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0028_remove_sucursal_from_anticipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='anticipo',
            name='monto_aplicado',
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=0,
                default_currency='MXN',
                help_text='Monto acumulado ya aplicado a ventas.',
                max_digits=10,
            ),
        ),
        migrations.AddConstraint(
            model_name='anticipo',
            constraint=models.CheckConstraint(
                condition=models.Q(monto_aplicado__gte=0),
                name='anticipo_monto_aplicado_no_negativo',
            ),
        ),
    ]
