# Generated by Django 5.2.4 on 2026-04-29

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0029_anticipo_monto_aplicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='anticipo',
            name='monto_aplicado_currency',
            field=djmoney.models.fields.CurrencyField(
                default='MXN',
                editable=False,
                max_length=3,
            ),
        ),
    ]
