# Generated by Django 5.2.4 on 2026-04-29 21:45

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0030_anticipo_monto_aplicado_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anticipo',
            name='monto_aplicado_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('AUD', 'Dólar Australiano (AUD)'), ('CAD', 'Dólar Canadiense (CAD)'), ('USD', 'Dólar Estadounidense (USD)'), ('EUR', 'Euro (EUR)'), ('CHF', 'Franco Suizo (CHF)'), ('GBP', 'Libra Esterlina (GBP)'), ('MXN', 'Peso Mexicano (MXN)'), ('INR', 'Rupia India (INR)'), ('JPY', 'Yen Japonés (JPY)'), ('CNY', 'Yuan Chino (CNY)')], default='MXN', editable=False, max_length=3),
        ),
    ]
