# Generated by Django 5.2.4 on 2026-05-07 06:24

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0031_alter_anticipo_monto_aplicado_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadocuentacliente',
            name='saldo_inicial',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), help_text='Saldo acumulado de ventas anteriores al inicio del período', max_digits=12),
        ),
        migrations.AddField(
            model_name='estadocuentacliente',
            name='saldo_inicial_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('AUD', 'Dólar Australiano (AUD)'), ('CAD', 'Dólar Canadiense (CAD)'), ('USD', 'Dólar Estadounidense (USD)'), ('EUR', 'Euro (EUR)'), ('CHF', 'Franco Suizo (CHF)'), ('GBP', 'Libra Esterlina (GBP)'), ('MXN', 'Peso Mexicano (MXN)'), ('INR', 'Rupia India (INR)'), ('JPY', 'Yen Japonés (JPY)'), ('CNY', 'Yuan Chino (CNY)')], default='MXN', editable=False, max_length=3),
        ),
    ]
