# Generated by Django 5.2.4 on 2026-06-10 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0032_add_saldo_inicial_to_estado_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldocliente',
            name='venta',
            field=models.OneToOneField(help_text='Venta que origina este saldo', on_delete=django.db.models.deletion.CASCADE, related_name='saldo_cxc', to='ventas.ventas'),
        ),
    ]
