# Generated by OpenCode on 2026-06-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0033_alter_saldocliente_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='agente_id',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='ventas.agente',
                verbose_name='Agente aduanal',
            ),
        ),
    ]
