# Generated by Django 6.0.7 on 2026-08-24 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0026_alter_saldomensual_mes'),
        ('ventas', '0034_make_ventas_agente_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='anticipo',
            name='es_remanente',
            field=models.BooleanField(default=False, help_text='Marca si este registro corresponde al CFDI de remanente de anticipo (saldo a favor del cliente).', verbose_name='Es remanente de anticipo'),
        ),
        migrations.AddField(
            model_name='anticipo',
            name='uuid_cfdi',
            field=models.CharField(blank=True, help_text='UUID (folio fiscal) del CFDI de anticipo/remanente.', max_length=36, null=True, verbose_name='UUID del CFDI de anticipo'),
        ),
        migrations.AddField(
            model_name='pagoventa',
            name='banco_origen',
            field=models.ForeignKey(blank=True, help_text='Banco del cliente desde el cual se depositó (ej: Bancomer, Santander).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gastos.banco', verbose_name='Banco origen del depósito'),
        ),
        migrations.AddField(
            model_name='pagoventa',
            name='folio_rep',
            field=models.CharField(blank=True, help_text='Folio del Recibo Electrónico de Pago (complemento de pago).', max_length=50, null=True, verbose_name='Folio REP'),
        ),
        migrations.AddField(
            model_name='pagoventa',
            name='uuid_rep',
            field=models.CharField(blank=True, help_text='UUID (folio fiscal) del Recibo Electrónico de Pago.', max_length=36, null=True, verbose_name='UUID REP'),
        ),
    ]
