# Generated by Django 6.0.7 on 2026-08-24 21:53

from decimal import Decimal

import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models


def backfill_documentos_cfdi(apps, schema_editor):
    """
    Migra los campos fiscales legacy de Ventas/Anticipo al nuevo modelo
    DocumentoCFDI antes de eliminarlos.
    """
    Ventas = apps.get_model('ventas', 'Ventas')
    Anticipo = apps.get_model('ventas', 'Anticipo')
    DocumentoCFDI = apps.get_model('ventas', 'DocumentoCFDI')

    from djmoney.money import Money

    # ── 1. Ventas → factura (ingreso) + notas de cargo/crédito ───────────
    for venta in Ventas.objects.all().iterator():
        cliente = venta.cliente
        moneda = venta.moneda_venta or 'MXN'
        currency = venta.monto.currency if hasattr(venta.monto, 'currency') else 'MXN'

        # Factura principal
        if venta.folio_factura or venta.fecha_emision_cfdi:
            subtipo = (
                'venta_exportacion' if venta.tipo_venta == 'Exportación'
                else 'venta_nacional'
            )
            DocumentoCFDI.objects.create(
                cliente=cliente,
                tipo='I',
                subtipo=subtipo,
                folio=venta.folio_factura or None,
                fecha_emision=venta.fecha_emision_cfdi,
                monto=venta.monto,
                moneda=moneda,
                tipo_cambio=venta.tipo_cambio,
                venta=venta,
            )

        # Nota de crédito (egreso): descuenta saldo, monto = |ajuste| si ajuste < 0
        if venta.nota_credito:
            monto_nc = abs(venta.ajuste or 0) if (venta.ajuste or 0) < 0 else Decimal('0')
            DocumentoCFDI.objects.create(
                cliente=cliente,
                tipo='E',
                subtipo='nota_credito',
                folio=venta.nota_credito,
                fecha_emision=venta.fecha_emision_cfdi,
                monto=Money(monto_nc, currency),
                moneda=moneda,
                venta=venta,
            )

        # Nota de cargo (ingreso): suma saldo, monto = ajuste si ajuste > 0
        if venta.nota_cargo:
            monto_ncg = venta.ajuste if (venta.ajuste or 0) > 0 else Decimal('0')
            DocumentoCFDI.objects.create(
                cliente=cliente,
                tipo='I',
                subtipo='nota_cargo',
                folio=venta.nota_cargo,
                fecha_emision=venta.fecha_emision_cfdi,
                monto=Money(monto_ncg, currency),
                moneda=moneda,
                venta=venta,
            )

        # CFDI cancelado (referencia a un folio previo)
        if venta.cfdi_cancelado:
            subtipo = (
                'venta_exportacion' if venta.tipo_venta == 'Exportación'
                else 'venta_nacional'
            )
            DocumentoCFDI.objects.create(
                cliente=cliente,
                tipo='I',
                subtipo=subtipo,
                folio=venta.cfdi_cancelado,
                monto=Money(Decimal('0'), currency),
                moneda=moneda,
                estado='CANCELADO',
                venta=venta,
            )

    # ── 2. Anticipos → remanente de anticipo ─────────────────────────────
    for anticipo in Anticipo.objects.exclude(folio_factura_anticipo__isnull=True).exclude(
        folio_factura_anticipo=''
    ).iterator():
        DocumentoCFDI.objects.create(
            cliente=anticipo.cliente,
            tipo='I',
            subtipo='remanente_anticipo',
            folio=anticipo.folio_factura_anticipo,
            fecha_emision=anticipo.fecha,
            monto=anticipo.monto,
            moneda=anticipo.monto.currency if hasattr(anticipo.monto, 'currency') else 'MXN',
            anticipo=anticipo,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0035_anticipo_es_remanente_anticipo_uuid_cfdi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoCFDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('I', 'Ingreso'), ('E', 'Egreso'), ('P', 'Pago (Recibo Electrónico)')], max_length=1)),
                ('subtipo', models.CharField(choices=[('venta_nacional', 'Venta Nacional'), ('venta_exportacion', 'Venta Exportación'), ('nota_cargo', 'Nota de Cargo'), ('remanente_anticipo', 'Remanente de Anticipo'), ('nota_credito', 'Nota de Crédito'), ('recibo_pago', 'Recibo Electrónico de Pago')], max_length=20)),
                ('serie', models.CharField(blank=True, max_length=25, null=True)),
                ('folio', models.CharField(blank=True, max_length=50, null=True)),
                ('uuid', models.CharField(blank=True, db_index=True, max_length=36, null=True, unique=True, verbose_name='UUID (folio fiscal)')),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_timbrado', models.DateTimeField(blank=True, null=True)),
                ('monto_currency', djmoney.models.fields.CurrencyField(choices=[('AUD', 'Dólar Australiano (AUD)'), ('CAD', 'Dólar Canadiense (CAD)'), ('USD', 'Dólar Estadounidense (USD)'), ('EUR', 'Euro (EUR)'), ('CHF', 'Franco Suizo (CHF)'), ('GBP', 'Libra Esterlina (GBP)'), ('MXN', 'Peso Mexicano (MXN)'), ('INR', 'Rupia India (INR)'), ('JPY', 'Yen Japonés (JPY)'), ('CNY', 'Yuan Chino (CNY)')], default='MXN', editable=False, max_length=3)),
                ('monto', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('moneda', models.CharField(default='MXN', max_length=3)),
                ('tipo_cambio', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('CANCELADO', 'Cancelado')], default='VIGENTE', max_length=10)),
                ('tipo_relacion', models.CharField(blank=True, help_text='Código SAT TipoRelacion (01 NC, 02 ND, 03 devolución, 07 anticipo...)', max_length=2, null=True)),
                ('archivo_xml', models.FileField(blank=True, null=True, upload_to='cfdi/xml/%Y/%m/')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='cfdi/pdf/%Y/%m/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('anticipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_cfdi', to='ventas.anticipo')),
                ('cfdi_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_relacionados', to='ventas.documentocfdi')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_cfdi', to='ventas.cliente')),
                ('pago_venta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documento_cfdi', to='ventas.pagoventa')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_cfdi', to='ventas.ventas')),
            ],
            options={
                'verbose_name': 'Documento CFDI',
                'verbose_name_plural': 'Documentos CFDI',
                'ordering': ['-fecha_emision', '-creado_en'],
                'indexes': [models.Index(fields=['cliente', 'fecha_emision'], name='ventas_docu_cliente_a292a6_idx'), models.Index(fields=['subtipo', 'estado'], name='ventas_docu_subtipo_67f2a2_idx'), models.Index(fields=['venta', 'subtipo', 'estado'], name='ventas_docu_venta_i_2c34f3_idx')],
            },
        ),
        migrations.RunPython(backfill_documentos_cfdi, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='anticipo',
            name='folio_factura_anticipo',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='ajuste',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='cfdi_cancelado',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='fecha_emision_cfdi',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='folio_factura',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='nota_cargo',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='nota_credito',
        ),
    ]
