# Generated by Django 6.0.7 on 2026-08-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0037_cliente_datos_fiscales'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentocfdi',
            name='conceptos',
            field=models.JSONField(blank=True, default=list, help_text='Lista de conceptos extraídos del XML (clave, descripción, cantidad, unidad...).', verbose_name='Conceptos'),
        ),
    ]
