# Generated by Django 6.0.7 on 2026-08-26 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0016_estado_pais'),
        ('ventas', '0038_documentocfdi_conceptos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentocfdi',
            name='subtipo',
            field=models.CharField(choices=[('venta_nacional', 'Venta Nacional'), ('venta_exportacion', 'Venta Exportación'), ('ingreso_servicio', 'Ingreso por Servicio'), ('ingreso_mixto', 'Ingreso Mixto (revisión)'), ('nota_cargo', 'Nota de Cargo'), ('remanente_anticipo', 'Remanente de Anticipo'), ('nota_credito', 'Nota de Crédito'), ('recibo_pago', 'Recibo Electrónico de Pago')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='producto',
            field=models.ForeignKey(blank=True, help_text='Requerido para ventas de producto; no aplica a servicios.', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='tipo_registro',
            field=models.CharField(choices=[('VENTA', 'Venta'), ('MAQUILA', 'Maquila'), ('SERVICIO', 'Servicio')], default='VENTA', help_text='Tipo de registro: venta, maquila o ingreso por servicio', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='ventas',
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(tipo_registro='SERVICIO', producto__isnull=True)
                    | models.Q(
                        tipo_registro__in=['VENTA', 'MAQUILA'],
                        producto__isnull=False,
                    )
                ),
                name='venta_producto_segun_tipo_registro',
            ),
        ),
    ]
