# Generated by Django 6.0.7 on 2026-09-23 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0028_alter_saldomensual_mes'),
        ('ventas', '0039_clasificar_ingresos_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gastos.cuenta'),
        ),
    ]
