# Generated by Django 5.1.15 on 2026-10-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0041_pagoventa_tipo_cambio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentocfdi',
            name='subtipo',
            field=models.CharField(choices=[('venta_nacional', 'Venta Nacional'), ('venta_exportacion', 'Venta Exportación'), ('ingreso_servicio', 'Ingreso por Servicio'), ('otros_ingresos', 'Otros Ingresos (sin CFDI)'), ('ingreso_mixto', 'Ingreso Mixto (revisión)'), ('nota_cargo', 'Nota de Cargo'), ('remanente_anticipo', 'Remanente de Anticipo'), ('nota_credito', 'Nota de Crédito'), ('recibo_pago', 'Recibo Electrónico de Pago')], max_length=20),
        ),
    ]
