# Generated by Django 5.2.4 on 2026-04-20 15:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinatarioReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Destinatario de reporte',
                'verbose_name_plural': 'Destinatarios de reporte',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Configuración principal', max_length=120, verbose_name='Nombre de configuración')),
                ('periodo_default', models.CharField(choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('anual', 'Anual'), ('personalizado', 'Personalizado')], default='mensual', max_length=20, verbose_name='Período por defecto')),
                ('asunto_email', models.CharField(default='Resumen Ejecutivo Financiero — {periodo}', help_text='Usa {periodo} para incluir el período automáticamente.', max_length=200, verbose_name='Asunto del correo')),
                ('modelo_ia', models.CharField(blank=True, help_text='Deja en blanco para usar GOOGLE_API_MODEL del entorno. Usa el formato proveedor/modelo para OpenRouter (ej: google/gemini-3.1-flash-lite-preview).', max_length=120, verbose_name='Modelo de IA')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('destinatarios', models.ManyToManyField(blank=True, help_text='Correos a los que se enviará el reporte.', to='reportes.destinatarioreporte', verbose_name='Destinatarios')),
            ],
            options={
                'verbose_name': 'Configuración de reporte',
                'verbose_name_plural': 'Configuración de reporte',
            },
        ),
        migrations.CreateModel(
            name='ReporteEjecutivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('periodo_inicio', models.DateField(verbose_name='Inicio del período')),
                ('periodo_fin', models.DateField(verbose_name='Fin del período')),
                ('total_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Total ventas')),
                ('total_gastos', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Total gastos')),
                ('total_compras', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Total compras')),
                ('margen_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Margen bruto')),
                ('margen_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Margen (%)')),
                ('resumen_ia', models.TextField(blank=True, verbose_name='Resumen generado por IA')),
                ('modelo_ia_usado', models.CharField(blank=True, max_length=120, verbose_name='Modelo de IA usado')),
                ('estado', models.CharField(choices=[('generando', 'Generando...'), ('generado', 'Generado'), ('enviando', 'Enviando...'), ('enviado', 'Enviado'), ('error', 'Error')], default='generando', max_length=20, verbose_name='Estado')),
                ('destinatarios_enviados', models.TextField(blank=True, help_text='Correos a los que se envió (JSON).', verbose_name='Destinatarios')),
                ('error_detalle', models.TextField(blank=True, verbose_name='Detalle del error')),
                ('fecha_generacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de generación')),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
            ],
            options={
                'verbose_name': 'Reporte ejecutivo',
                'verbose_name_plural': 'Reportes ejecutivos',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
