# Generated by Django 5.2.4 on 2026-05-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteejecutivo',
            name='proyecciones_json',
            field=models.TextField(blank=True, help_text='Proyecciones financieras generadas con scikit-learn (JSON).', verbose_name='Proyecciones de ventas (scikit-learn)'),
        ),
    ]
