# Generated by Django 5.2.4 on 2026-06-21 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reportes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinatarioWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('telefono', models.CharField(help_text="Numero con codigo de pais, sin '+', ej: 5216671234567.", max_length=30, unique=True, verbose_name='Telefono')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('notas', models.TextField(blank=True, help_text='Informacion adicional sobre este contacto.', verbose_name='Notas')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Destinatario WhatsApp',
                'verbose_name_plural': 'Destinatarios WhatsApp',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EvolutionInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(help_text='Nombre o ID de la instancia en Evolution API (ej: ddcdaf19-e686-47d2-b7f3-1a3d12a31611).', max_length=255, unique=True, verbose_name='ID de instancia')),
                ('nombre', models.CharField(help_text='Nombre descriptivo para identificar esta instancia en el sistema.', max_length=255, verbose_name='Nombre')),
                ('api_url', models.URLField(help_text='URL base del servidor Evolution API (ej: https://agricola-evolutionapi-...sslip.io).', max_length=500, verbose_name='URL de Evolution API')),
                ('apikey', models.CharField(help_text="Clave de API para autenticar con Evolution (se envia en header 'apikey').", max_length=255, verbose_name='API Key')),
                ('webhook_url', models.URLField(blank=True, help_text='URL donde Evolution enviara los eventos entrantes. Se configura automaticamente si se deja en blanco.', max_length=500, verbose_name='URL del webhook')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('estado', models.CharField(choices=[('conectado', 'Conectado'), ('desconectado', 'Desconectado'), ('error', 'Error')], default='desconectado', max_length=20, verbose_name='Estado')),
                ('ultima_verificacion', models.DateTimeField(blank=True, null=True, verbose_name='Ultima verificacion')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'Instancia Evolution',
                'verbose_name_plural': 'Instancias Evolution',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('enviar_reportes', models.BooleanField(default=True, verbose_name='Enviar reportes ejecutivos')),
                ('enviar_alertas', models.BooleanField(default=True, help_text='Alertas de cobranza, vencimientos, etc.', verbose_name='Enviar alertas')),
                ('frecuencia_envio', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('manual', 'Solo manual')], default='mensual', max_length=20, verbose_name='Frecuencia de envio')),
                ('hora_envio', models.TimeField(default='08:00', help_text='Hora del dia en que se enviaran los reportes (formato 24h).', verbose_name='Hora de envio')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado'), (7, 'Domingo')], default=1, help_text='1=Lunes, 7=Domingo. Solo aplica para frecuencia semanal.', verbose_name='Dia de la semana')),
                ('dia_mes', models.PositiveSmallIntegerField(default=1, help_text='1-28. Solo aplica para frecuencia mensual.', verbose_name='Dia del mes')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('usuario', models.OneToOneField(blank=True, help_text='Dejar en blanco para configuracion global.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config_whatsapp', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('destinatarios', models.ManyToManyField(blank=True, help_text='Contactos a los que se enviaran los reportes y alertas.', to='whatsapp.destinatariowhatsapp', verbose_name='Destinatarios')),
                ('instancia', models.ForeignKey(help_text='Instancia de WhatsApp a usar para el envio.', on_delete=django.db.models.deletion.PROTECT, to='whatsapp.evolutioninstance', verbose_name='Instancia Evolution')),
            ],
            options={
                'verbose_name': 'Configuracion WhatsApp',
                'verbose_name_plural': 'Configuraciones WhatsApp',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='MensajeWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('reporte', 'Reporte ejecutivo'), ('alerta', 'Alerta'), ('manual', 'Manual'), ('prueba', 'Prueba')], default='manual', max_length=20, verbose_name='Tipo de mensaje')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('error', 'Error')], default='pendiente', max_length=20, verbose_name='Estado de envio')),
                ('evolution_message_id', models.CharField(blank=True, help_text='Identificador retornado por Evolution API.', max_length=255, verbose_name='ID del mensaje en Evolution')),
                ('error_detalle', models.TextField(blank=True, verbose_name='Detalle del error')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envio')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='whatsapp.destinatariowhatsapp', verbose_name='Destinatario')),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='whatsapp.evolutioninstance', verbose_name='Instancia')),
                ('reporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_whatsapp', to='reportes.reporteejecutivo', verbose_name='Reporte asociado')),
            ],
            options={
                'verbose_name': 'Mensaje WhatsApp',
                'verbose_name_plural': 'Mensajes WhatsApp',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='ProgramacionEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_ejecucion', 'En ejecucion'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('programado_para', models.DateTimeField(verbose_name='Programado para')),
                ('ejecutado_en', models.DateTimeField(blank=True, null=True, verbose_name='Ejecutado en')),
                ('error_detalle', models.TextField(blank=True, verbose_name='Detalle del error')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaciones', to='whatsapp.configuracionwhatsapp', verbose_name='Configuracion')),
                ('reporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios_whatsapp', to='reportes.reporteejecutivo', verbose_name='Reporte ejecutivo')),
            ],
            options={
                'verbose_name': 'Programacion de envio',
                'verbose_name_plural': 'Programaciones de envio',
                'ordering': ['-programado_para'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(help_text='Ej: messages-upsert, qrcode.updated, connection.update.', max_length=50, verbose_name='Tipo de evento')),
                ('payload', models.JSONField(help_text='Datos completos recibidos del webhook.', verbose_name='Payload completo')),
                ('telefono_remitente', models.CharField(blank=True, max_length=30, verbose_name='Telefono remitente')),
                ('mensaje', models.TextField(blank=True, verbose_name='Mensaje recibido')),
                ('procesado', models.BooleanField(default=False, help_text='Indica si el evento ya fue procesado por el sistema.', verbose_name='Procesado')),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de recepcion')),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='whatsapp.evolutioninstance', verbose_name='Instancia')),
            ],
            options={
                'verbose_name': 'Log de webhook',
                'verbose_name_plural': 'Logs de webhooks',
                'ordering': ['-fecha_recepcion'],
            },
        ),
    ]
