# Generated by Django 5.2.4 on 2025-10-12 19:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0016_estado_pais'),
        ('gastos', '0022_alter_compra_monto_total_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatInversion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, verbose_name='Categoría Activa')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Categoría de Inversión',
                'verbose_name_plural': 'Categorías de Inversión',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Inversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada de Capital'), ('SALIDA', 'Salida de Capital (Inversión)')], default='SALIDA', max_length=10, verbose_name='Tipo de Movimiento')),
                ('monto_currency', djmoney.models.fields.CurrencyField(choices=[('AUD', 'Dólar Australiano (AUD)'), ('CAD', 'Dólar Canadiense (CAD)'), ('USD', 'Dólar Estadounidense (USD)'), ('EUR', 'Euro (EUR)'), ('CHF', 'Franco Suizo (CHF)'), ('GBP', 'Libra Esterlina (GBP)'), ('MXN', 'Peso Mexicano (MXN)'), ('INR', 'Rupia India (INR)'), ('JPY', 'Yen Japonés (JPY)'), ('CNY', 'Yuan Chino (CNY)')], default='MXN', editable=False, max_length=3)),
                ('monto', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Movimiento')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('documento_soporte', models.FileField(blank=True, help_text='Subir contrato, comprobante o documento relacionado (PDF, Word, Excel, imágenes)', null=True, upload_to='capital_inversiones/documentos/%Y/%m/', verbose_name='Documento de Soporte')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro en Sistema')),
                ('ultima_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('id_cat_inversion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='capital_inversiones.catinversion', verbose_name='Categoría de Inversión')),
                ('id_cuenta_banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastos.cuenta', verbose_name='Cuenta Bancaria')),
                ('id_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Inversión',
                'verbose_name_plural': 'Inversiones y Capital',
                'ordering': ['-fecha', '-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='RendimientoInversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_rendimiento', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Rendimiento')),
                ('monto_rendimiento_currency', djmoney.models.fields.CurrencyField(choices=[('AUD', 'Dólar Australiano (AUD)'), ('CAD', 'Dólar Canadiense (CAD)'), ('USD', 'Dólar Estadounidense (USD)'), ('EUR', 'Euro (EUR)'), ('CHF', 'Franco Suizo (CHF)'), ('GBP', 'Libra Esterlina (GBP)'), ('MXN', 'Peso Mexicano (MXN)'), ('INR', 'Rupia India (INR)'), ('JPY', 'Yen Japonés (JPY)'), ('CNY', 'Yuan Chino (CNY)')], default='MXN', editable=False, max_length=3)),
                ('monto_rendimiento', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto del Rendimiento')),
                ('porcentaje_rendimiento', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de rendimiento calculado', max_digits=5, null=True, verbose_name='% Rendimiento')),
                ('tipo_rendimiento', models.CharField(blank=True, help_text='Ej: Dividendo, Interés, Ganancia de Capital, etc.', max_length=50, null=True, verbose_name='Tipo de Rendimiento')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('inversion', models.ForeignKey(limit_choices_to={'tipo_movimiento': 'SALIDA'}, on_delete=django.db.models.deletion.CASCADE, related_name='rendimientos', to='capital_inversiones.inversion', verbose_name='Inversión Relacionada')),
            ],
            options={
                'verbose_name': 'Rendimiento de Inversión',
                'verbose_name_plural': 'Rendimientos de Inversiones',
                'ordering': ['-fecha_rendimiento'],
            },
        ),
        migrations.AddIndex(
            model_name='inversion',
            index=models.Index(fields=['-fecha', 'id_sucursal'], name='capital_inv_fecha_58d189_idx'),
        ),
        migrations.AddIndex(
            model_name='inversion',
            index=models.Index(fields=['tipo_movimiento', 'fecha'], name='capital_inv_tipo_mo_398955_idx'),
        ),
        migrations.AddIndex(
            model_name='inversion',
            index=models.Index(fields=['id_cat_inversion', 'fecha'], name='capital_inv_id_cat__f6dcbb_idx'),
        ),
    ]
