# Generated by Django 5.2.4 on 2025-10-12 20:00

import djmoney.models.fields
import djmoney.models.validators
import djmoney.money
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capital_inversiones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inversion',
            name='monto',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, validators=[djmoney.models.validators.MinMoneyValidator(djmoney.money.Money('0.01', 'MXN'))], verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='rendimientoinversion',
            name='monto_rendimiento',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, validators=[djmoney.models.validators.MinMoneyValidator(djmoney.money.Money('0.00', 'MXN'))], verbose_name='Monto del Rendimiento'),
        ),
    ]
