# Generated by Django 5.0.6 on 2024-07-31 21:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0002_remove_registro_id_cat_gastos_and_more"),
        ("gastos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banco",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=50)),
                ("telefono", models.CharField(blank=True, max_length=15, null=True)),
                ("direccion", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "fecha_registro",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="sucursal",
            name="id_estado",
        ),
        migrations.RemoveField(
            model_name="gasto",
            name="id_cat_gastos",
        ),
        migrations.RemoveField(
            model_name="gasto",
            name="id_sucursal",
        ),
        migrations.CreateModel(
            name="Cuenta",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("numero_cuenta", models.CharField(max_length=25)),
                ("saldo", models.FloatField()),
                (
                    "fecha_registro",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "id_banco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gastos.banco"
                    ),
                ),
                (
                    "id_sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogo.sucursal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gastos",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("monto", models.FloatField()),
                (
                    "fecha_registro",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("fecha", models.DateField()),
                (
                    "id_cat_gastos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gastos.catgastos",
                    ),
                ),
                (
                    "id_cuenta_banco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gastos.cuenta"
                    ),
                ),
                (
                    "id_sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogo.sucursal",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Estado",
        ),
        migrations.DeleteModel(
            name="Gasto",
        ),
        migrations.DeleteModel(
            name="Sucursal",
        ),
    ]
