# Generated by Django 5.0.6 on 2024-08-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gastos", "0002_banco_remove_sucursal_id_estado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banco",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="catgastos",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="cuenta",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="gastos",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
