# Generated by Django 5.0.6 on 2024-08-01 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gastos", "0003_alter_banco_id_alter_catgastos_id_alter_cuenta_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="banco",
            options={"ordering": ["nombre"], "verbose_name_plural": "Bancos"},
        ),
        migrations.AlterModelOptions(
            name="catgastos",
            options={
                "ordering": ["nombre"],
                "verbose_name_plural": "Categorías de Gastos",
            },
        ),
        migrations.AlterModelOptions(
            name="cuenta",
            options={"ordering": ["-fecha_registro"], "verbose_name_plural": "Cuentas"},
        ),
        migrations.AlterModelOptions(
            name="gastos",
            options={"ordering": ["-fecha_registro"], "verbose_name_plural": "Gastos"},
        ),
    ]
