# Generated by Django 5.0.6 on 2024-08-01 21:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gastos", "0004_alter_banco_options_alter_catgastos_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="banco",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Banco",
                "verbose_name_plural": "Bancos",
            },
        ),
        migrations.AlterModelOptions(
            name="cuenta",
            options={
                "ordering": ["-fecha_registro"],
                "verbose_name": "Cuenta",
                "verbose_name_plural": "Cuentas",
            },
        ),
        migrations.AlterModelOptions(
            name="gastos",
            options={
                "ordering": ["-fecha_registro"],
                "verbose_name": "Gasto",
                "verbose_name_plural": "Gastos",
            },
        ),
        migrations.AddField(
            model_name="catgastos",
            name="fecha_registro",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="catgastos",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
