# Generated by Django 5.0.6 on 2024-08-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gastos", "0005_alter_banco_options_alter_cuenta_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cuenta",
            name="saldo",
        ),
        migrations.AddField(
            model_name="cuenta",
            name="clabe",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="cuenta",
            name="numero_cliente",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="cuenta",
            name="rfc",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
