# Generated by Django 5.1.3 on 2024-11-09 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_pais_moneda'),
        ('gastos', '0006_remove_cuenta_saldo_cuenta_clabe_and_more'),
        ('ventas', '0003_ventas_pedimento_alter_ventas_po_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField()),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.producto')),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.productor')),
            ],
            options={
                'verbose_name_plural': 'Compras',
            },
        ),
    ]
