# Generated by Django 5.1.3 on 2024-12-08 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0008_alter_compra_options_alter_compra_fecha_registro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['-fecha_compra'], 'verbose_name': 'Compra de fruta', 'verbose_name_plural': 'Compras de fruta'},
        ),
        migrations.AddField(
            model_name='compra',
            name='cuenta',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='gastos.cuenta'),
        ),
    ]
