# Generated by Django 5.1.3 on 2024-12-30 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0010_alter_compra_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['-fecha_compra'], 'permissions': [('can_view_compras', 'Can view compras')], 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras de fruta'},
        ),
        migrations.CreateModel(
            name='SaldoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.PositiveIntegerField()),
                ('mes', models.PositiveIntegerField()),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastos.cuenta')),
            ],
            options={
                'verbose_name': 'Saldo Mensual',
                'verbose_name_plural': 'Saldos Mensuales',
                'unique_together': {('cuenta', 'año', 'mes')},
            },
        ),
    ]
