# Generated by Django 5.1.3 on 2024-12-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0012_alter_catgastos_options_alter_saldomensual_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='tipo_pago',
            field=models.CharField(blank=True, choices=[('Efectivo', 'Efectivo'), ('Deposito', 'Deposito'), ('Transferencia', 'Transferencia'), ('Cheque', 'Cheque')], max_length=50, null=True),
        ),
    ]
