# Generated by Django 5.1.3 on 2025-01-10 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_producto'),
        ('gastos', '0016_alter_saldomensual_año_alter_saldomensual_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto'),
        ),
    ]
