# Generated by Django 5.1.3 on 2025-01-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0017_alter_compra_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='logotipo',
            field=models.ImageField(blank=True, help_text='Subir imagen con formato .jpg, .jpeg o .png', null=True, upload_to='bancos/logos/', verbose_name='Logotipo del Banco'),
        ),
    ]
