# Generated by Django 5.1.3 on 2025-01-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0020_alter_catgastos_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catgastos',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
