# Generated by Django 5.2.4 on 2025-10-12 19:38

import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0021_compra_monto_total_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='monto_total_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('AUD', 'Dólar Australiano (AUD)'), ('CAD', 'Dólar Canadiense (CAD)'), ('USD', 'Dólar Estadounidense (USD)'), ('EUR', 'Euro (EUR)'), ('CHF', 'Franco Suizo (CHF)'), ('GBP', 'Libra Esterlina (GBP)'), ('MXN', 'Peso Mexicano (MXN)'), ('INR', 'Rupia India (INR)'), ('JPY', 'Yen Japonés (JPY)'), ('CNY', 'Yuan Chino (CNY)')], default='MXN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='compra',
            name='precio_unitario_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('AUD', 'Dólar Australiano (AUD)'), ('CAD', 'Dólar Canadiense (CAD)'), ('USD', 'Dólar Estadounidense (USD)'), ('EUR', 'Euro (EUR)'), ('CHF', 'Franco Suizo (CHF)'), ('GBP', 'Libra Esterlina (GBP)'), ('MXN', 'Peso Mexicano (MXN)'), ('INR', 'Rupia India (INR)'), ('JPY', 'Yen Japonés (JPY)'), ('CNY', 'Yuan Chino (CNY)')], default='MXN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='monto_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('AUD', 'Dólar Australiano (AUD)'), ('CAD', 'Dólar Canadiense (CAD)'), ('USD', 'Dólar Estadounidense (USD)'), ('EUR', 'Euro (EUR)'), ('CHF', 'Franco Suizo (CHF)'), ('GBP', 'Libra Esterlina (GBP)'), ('MXN', 'Peso Mexicano (MXN)'), ('INR', 'Rupia India (INR)'), ('JPY', 'Yen Japonés (JPY)'), ('CNY', 'Yuan Chino (CNY)')], default='MXN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='saldomensual',
            name='mes',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=10),
        ),
        migrations.AlterField(
            model_name='saldomensual',
            name='saldo_final_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('AUD', 'Dólar Australiano (AUD)'), ('CAD', 'Dólar Canadiense (CAD)'), ('USD', 'Dólar Estadounidense (USD)'), ('EUR', 'Euro (EUR)'), ('CHF', 'Franco Suizo (CHF)'), ('GBP', 'Libra Esterlina (GBP)'), ('MXN', 'Peso Mexicano (MXN)'), ('INR', 'Rupia India (INR)'), ('JPY', 'Yen Japonés (JPY)'), ('CNY', 'Yuan Chino (CNY)')], default='MXN', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='saldomensual',
            name='saldo_inicial_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('AUD', 'Dólar Australiano (AUD)'), ('CAD', 'Dólar Canadiense (CAD)'), ('USD', 'Dólar Estadounidense (USD)'), ('EUR', 'Euro (EUR)'), ('CHF', 'Franco Suizo (CHF)'), ('GBP', 'Libra Esterlina (GBP)'), ('MXN', 'Peso Mexicano (MXN)'), ('INR', 'Rupia India (INR)'), ('JPY', 'Yen Japonés (JPY)'), ('CNY', 'Yuan Chino (CNY)')], default='MXN', editable=False, max_length=3),
        ),
    ]
