# Generated by Django 5.1.3 on 2025-02-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0021_catgastos_fecha_modificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldomensual',
            name='mes',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=2),
        ),
    ]
