# Generated by Django 5.2.4 on 2025-12-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0022_alter_compra_monto_total_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldomensual',
            name='mes',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=12),
        ),
    ]
