# Generated by Django 5.1.6 on 2025-03-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0022_alter_saldomensual_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='saldomensual',
            name='mes',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=3),
        ),
    ]
