# Generated by Django 5.2.4 on 2026-07-11 17:25

import django.db.models.deletion
import gastos.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0024_alter_saldomensual_año_alter_saldomensual_mes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('archivo', models.FileField(upload_to=gastos.models.comprobante_upload_path)),
                ('nombre_original', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('tamano_bytes', models.PositiveIntegerField()),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('estado', models.CharField(choices=[('pending', 'Pendiente de procesar'), ('processing', 'Procesando'), ('review', 'Listo para revisi?n'), ('error', 'Error de procesamiento'), ('recorded', 'Gasto registrado')], db_index=True, default='pending', max_length=16)),
                ('datos_extraidos', models.JSONField(blank=True, default=dict)),
                ('texto_ocr', models.TextField(blank=True)),
                ('confianza', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('error_procesamiento', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('procesado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('gasto', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobante', to='gastos.gastos')),
            ],
            options={
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['estado', 'creado_en'], name='gastos_comp_estado_fecha_idx'), models.Index(fields=['sha256', 'creado_en'], name='gastos_comp_hash_fecha_idx')],
            },
        ),
    ]
